// GRE-specific prefix/root reference, transcribed from the user's own GRE
// vocab course material (30 prefixes + 90 roots, each with a meaning, a
// memorable "hint word", and real GRE-level example words). Used by
// mnemonic.js to recognize a prefix/root inside a word and surface it as
// part of the auto-generated mnemonic — this is the same word-building
// technique the course book itself teaches, just applied automatically.
export const GRE_PREFIXES = [
  { forms: ["ab", "abs", "apo"], meaning: "遠離、脫離 (away from, off)", examples: ["aberrant", "abhor", "abstemious", "abstruse", "apogee", "avert"] },
  { forms: ["ad", "ac", "af", "ag", "al", "an", "ap", "ar", "as", "at"], meaning: "向 (to, toward)", examples: ["adhere", "aggrandize", "appease", "assimilate", "attuned"] },
  { forms: ["ambi", "amphi"], meaning: "雙邊、周圍 (both sides, around)", examples: ["ambient", "ambiguous", "ambivalent"] },
  { forms: ["an"], meaning: "沒有 (without)", examples: ["amorphous", "anonymous", "apathetic"] },
  { forms: ["ante"], meaning: "先前 (before)", examples: ["antecedent", "antediluvian"] },
  { forms: ["ben", "bon"], meaning: "好 (good)", examples: ["benefactor", "benevolent"] },
  { forms: ["circum"], meaning: "環繞 (around)", examples: ["circumspect", "circumvent"] },
  { forms: ["con", "co", "col", "com", "cor"], meaning: "一起、共同 (with, together)", examples: ["coalesce", "collude", "commiserate", "consolidate", "corroborate"] },
  { forms: ["contra", "contro", "counter"], meaning: "相反 (against)", examples: ["contradict", "controvert", "counterfeit", "countermand"] },
  { forms: ["de"], meaning: "向下、分離 (down, away)", examples: ["delineate", "denigrate", "deprecate"] },
  { forms: ["dis", "dif"], meaning: "不、分離 (not, apart)", examples: ["diffident", "discord", "disparate"] },
  { forms: ["du", "di", "dicho"], meaning: "二 (two)", examples: ["dilemma", "dubious", "duplicity", "dichotomy"] },
  { forms: ["en", "em", "im", "in"], meaning: "使 (make)", examples: ["embellish", "enfeeble", "impassioned", "imperil", "ingratiating", "invigorate"] },
  { forms: ["equ", "eg"], meaning: "相等 (even)", examples: ["egalitarian", "equanimity", "equivocal"] },
  { forms: ["ex", "ec", "ef"], meaning: "向外 (out)", examples: ["eclectic", "effusive", "erudite", "explicable"] },
  { forms: ["eu", "ev"], meaning: "好 (good)", examples: ["eulogize", "euphemism", "evangelist"] },
  { forms: ["hetero"], meaning: "相異 (different)", examples: ["heterodox", "heterogeneous"] },
  { forms: ["homo"], meaning: "相同 (same)", examples: ["homogeneous"] },
  { forms: ["ob", "op"], meaning: "相反、在前面 (against, in front of)", examples: ["obdurate", "obloquy", "obviate", "obtrusive", "opprobrium"] },
  { forms: ["omni"], meaning: "全部 (all)", examples: ["omnipotent", "omnipresent", "omniscient", "omnivorous"] },
  { forms: ["para"], meaning: "在旁邊、相反 (beside, against)", examples: ["paradox", "parallel"] },
  { forms: ["peri"], meaning: "周圍 (around)", examples: ["peripatetic", "peripheral"] },
  { forms: ["pre"], meaning: "先前 (before)", examples: ["precocious", "precursor", "prescient"] },
  { forms: ["pro", "por"], meaning: "向前 (forward)", examples: ["portend", "profuse", "prolix", "prolonged"] },
  { forms: ["per", "pel"], meaning: "穿過、完全 (through, thoroughly)", examples: ["pellucid", "perennial", "pernicious", "perspicacious"] },
  { forms: ["re"], meaning: "向後、再 (back, again)", examples: ["recapitulate", "reiterate", "retract"] },
  { forms: ["sub", "suc", "suf", "sug", "sum", "sup", "sus", "sur"], meaning: "在下面 (under)", examples: ["substantiate", "succumb", "surreptitious", "susceptible"] },
  { forms: ["super", "sur"], meaning: "在...之上 (over, above)", examples: ["superfluous", "supersede", "surfeit"] },
  { forms: ["syn", "sym"], meaning: "一起、相同 (together, same)", examples: ["symmetric", "sympathetic", "synonymous", "synopsis", "synthesis"] },
  { forms: ["trans"], meaning: "橫越、超出 (across, beyond)", examples: ["transcend", "transgress", "transient"] },
];

export const GRE_ROOTS = [
  { forms: ["ac", "acr"], meaning: "尖、酸、苦 (sharp, sour, bitter)", hint: "acid 酸", examples: ["acerbic", "acme", "acrimony", "acumen", "acute", "exacerbate"] },
  { forms: ["anim"], meaning: "心智、靈魂 (mind, soul)", hint: "animal 動物", examples: ["animadversion", "animosity", "equanimity", "magnanimous", "unanimous"] },
  { forms: ["anthrop"], meaning: "人類 (human)", hint: "anthropology 人類學", examples: ["anthropomorphism", "anthropogenic", "misanthropic", "philanthropy"] },
  { forms: ["av"], meaning: "慾望 (desire)", examples: ["avaricious", "avid"] },
  { forms: ["av"], meaning: "鳥 (bird)", hint: "aviation 飛行", examples: ["auspicious"] },
  { forms: ["bell"], meaning: "戰爭 (war)", hint: "rebellious 叛逆的", examples: ["bellicose", "belligerent", "rebellious"] },
  { forms: ["bell"], meaning: "美 (beauty)", hint: "belle 美女", examples: ["embellish"] },
  { forms: ["capit", "cipit"], meaning: "頭 (head)", hint: "capital 首都", examples: ["capitulate", "recapitulate", "precipitate"] },
  { forms: ["cede", "ceed", "cess"], meaning: "行進 (go)", hint: "exceed 超過", examples: ["accede", "antecedent", "cede", "concede", "concession", "precedence", "precedent", "recede", "unprecedented"] },
  { forms: ["clud", "clus"], meaning: "關閉 (close)", hint: "include 包含", examples: ["conclusive", "exclusive", "occlude", "preclude", "reclusive", "seclude"] },
  { forms: ["cogn", "gno"], meaning: "知道 (know)", hint: "recognize 認出", examples: ["cognition", "cognizant", "connoisseur", "incognito", "prognosis"] },
  { forms: ["cord"], meaning: "心 (heart)", hint: "record 記錄", examples: ["accord", "concord", "cordial", "discord"] },
  { forms: ["cre"], meaning: "成長 (grow)", hint: "increase 增加", examples: ["accretion", "crescendo", "increment"] },
  { forms: ["cred"], meaning: "相信 (believe)", hint: "credit 信用", examples: ["credence", "credential", "credible", "credulous", "discredit", "incredulity"] },
  { forms: ["culp"], meaning: "罪 (crime)", examples: ["culpable", "culprit", "exculpate"] },
  { forms: ["cumb", "cub"], meaning: "躺臥、負擔 (lie, burden)", hint: "succumb 屈服", examples: ["cumbersome", "encumber", "incubate", "incumbent"] },
  { forms: ["cur", "cour", "cor"], meaning: "跑 (run)", hint: "occur 發生", examples: ["concur", "cursory", "discursive", "incur", "incursion", "precursor", "recourse", "recurrent", "succor"] },
  { forms: ["dic", "dict"], meaning: "說 (say)", hint: "predict 預言", examples: ["abdicate", "contradict", "dictate", "dictum", "indict", "predicament", "predicate", "valediction", "vindicate"] },
  { forms: ["doc", "dog", "dox", "dac"], meaning: "教導、意見 (teach, opinion)", hint: "doctor 醫生", examples: ["autodidact", "didactic", "docile", "doctrinaire", "dogmatic", "heterodox", "indoctrinate", "orthodox", "paradox"] },
  { forms: ["duc"], meaning: "引導 (lead)", hint: "education 教育", examples: ["adduce", "conducive", "deduce", "induce", "seduce", "subdue", "traduce"] },
  { forms: ["err"], meaning: "迷失方向 (go astray)", hint: "error 錯誤", examples: ["aberrant", "errant", "erratic", "erroneous", "unerring"] },
  { forms: ["esce"], meaning: "變為 (become)", hint: "adolescence 青春期", examples: ["acquiescence", "coalesce", "evanescent", "irascible", "quiescent", "recrudescent", "senescent"] },
  { forms: ["fa", "fess", "phe"], meaning: "說 (say)", hint: "fable 寓言故事", examples: ["affable", "euphemism", "ineffable", "nefarious", "profess", "prophetic"] },
  { forms: ["fac", "fec", "feit", "fic", "fy"], meaning: "做、製造 (do, make)", hint: "manufacture 製造", examples: ["affectation", "benefactor", "counterfeit", "demystify", "edifying", "facile", "facilitate", "feckless", "gratify", "mollify", "munificent", "nullify", "officious", "petrify", "prolific", "stupefy", "surfeit", "vilify"] },
  { forms: ["fid"], meaning: "信任 (trust)", hint: "confidence 自信", examples: ["confide", "diffident", "fidelity", "perfidious"] },
  { forms: ["flu"], meaning: "流動 (flow)", hint: "fluent 流暢的", examples: ["affluent", "effluence", "fluctuate", "influx", "superfluous"] },
  { forms: ["frac", "frag"], meaning: "破碎 (break)", hint: "fragile 脆弱的", examples: ["fraction", "fractious", "fragmentary", "infraction", "refraction", "refractory"] },
  { forms: ["fus"], meaning: "傾倒、融合 (pour, melt)", hint: "fusion 融合", examples: ["diffuse", "effusive", "infuse", "profuse"] },
  { forms: ["gen"], meaning: "出生 (birth)", hint: "gene 基因", examples: ["anthropogenic", "congenial", "degenerate", "disingenuous", "engender", "exogenous", "genial", "germane", "germinate", "heterogeneous", "homogeneous", "indigenous", "ingenious"] },
  { forms: ["grand"], meaning: "大 (great)", hint: "grand 雄偉的", examples: ["aggrandize", "grandeur", "grandiloquent", "grandiose"] },
  { forms: ["grat"], meaning: "快樂 (pleasing)", hint: "congratulate 恭喜", examples: ["gratifying", "gratuitous", "ingratiating"] },
  { forms: ["greg"], meaning: "聚集、團體 (gather, group)", hint: "segregation 隔離", examples: ["aggregate", "congregate", "egregious", "gregarious"] },
  { forms: ["ject"], meaning: "投擲 (throw)", hint: "reject 拒絕", examples: ["abject", "conjecture", "dejected", "jettison", "trajectory"] },
  { forms: ["lect", "lig"], meaning: "選擇 (choose)", hint: "select 選擇", examples: ["eclectic", "eligible", "negligent", "negligible", "predilection"] },
  { forms: ["lev", "liev"], meaning: "輕、抬 (light)", hint: "relieve 減輕", examples: ["alleviate", "elevate", "levity"] },
  { forms: ["locu", "loqu", "log"], meaning: "說 (speak)", hint: "colloquial 口語的", examples: ["analogy", "circumlocution", "eulogy", "eloquent", "grandiloquent", "ideologue", "loquacious", "obloquy", "soliloquy"] },
  { forms: ["luc", "lumin", "lustr"], meaning: "光亮 (bright)", hint: "luminous 發光的", examples: ["elucidate", "illuminating", "illustrious", "lucid", "luminary", "lackluster", "pellucid"] },
  { forms: ["lud", "lus"], meaning: "玩弄 (play)", hint: "illusion 幻覺", examples: ["allude", "collude", "delude", "elude", "elusive", "illusory", "ludicrous"] },
  { forms: ["nay", "neg", "nih", "nul"], meaning: "不 (not)", hint: "negative 否定的", examples: ["abnegate", "annihilate", "annul", "naysayer", "nefarious", "negligible", "negate", "nihilism", "nullify", "renegade"] },
  { forms: ["noc", "nox", "nic"], meaning: "毒害 (poison)", hint: "innocent 無辜的", examples: ["innocuous", "noxious", "obnoxious", "pernicious"] },
  { forms: ["nounc", "nunc"], meaning: "宣佈 (declare)", hint: "announce 宣佈", examples: ["denounce", "denunciation", "pronounced", "renounce", "renunciation"] },
  { forms: ["oner"], meaning: "負擔 (burden)", examples: ["exonerate", "onerous", "onus"] },
  { forms: ["path", "pass"], meaning: "情感 (feeling)", hint: "pathetic 可憐的", examples: ["antipathy", "apathetic", "dispassionate", "impassioned", "impassive", "sympathetic"] },
  { forms: ["pecc"], meaning: "錯誤 (fault)", examples: ["impeccable", "peccadillo"] },
  { forms: ["pecu"], meaning: "錢 (money)", examples: ["impecunious", "pecuniary"] },
  { forms: ["ped", "pud"], meaning: "腳 (foot)", hint: "pedestrian 行人", examples: ["expedient", "expedite", "impede", "pedigree", "repudiate"] },
  { forms: ["pel", "pul"], meaning: "推 (push)", hint: "expel 驅逐", examples: ["compelling", "repellent", "repulsive"] },
  { forms: ["pen", "pun"], meaning: "痛苦、處罰 (pain, punish)", hint: "penalty 懲罰", examples: ["impunity", "penance", "penitential", "repentant", "punitive"] },
  { forms: ["pend", "pens"], meaning: "懸掛 (hang)", hint: "pendulum 鐘擺", examples: ["compendium", "penchant", "pensive", "propensity"] },
  { forms: ["plac"], meaning: "滿意 (please)", hint: "placid 平靜的", examples: ["complacent", "complaisant", "implacable", "placate", "placebo"] },
  { forms: ["pli", "plic", "ple"], meaning: "折 (fold)", hint: "complicated 複雜的", examples: ["duplicate", "duplicity", "explicate", "explicit", "inexplicable", "implicit", "pliable", "pliant", "replicate", "supple", "supplication"] },
  { forms: ["plor"], meaning: "哭 (cry)", examples: ["deplore", "implore"] },
  { forms: ["pos", "pound"], meaning: "放置 (place)", hint: "disposal 清除", examples: ["apposite", "composure", "compound", "depose", "disposition", "exposition", "expound", "juxtaposition", "posit", "propound", "supposition"] },
  { forms: ["prehend", "prehens"], meaning: "抓 (seize)", hint: "comprehension 理解", examples: ["apprehension", "comprehensive", "reprehend"] },
  { forms: ["punc", "pung", "pugn"], meaning: "刺、搏鬥 (prick, fight)", hint: "puncture 刺穿", examples: ["compunction", "expunge", "impugn", "poignant", "pugnacious", "punctilious", "pungent", "repugnant"] },
  { forms: ["rap", "rav", "rep"], meaning: "抓 (grasp)", hint: "rape 強姦", examples: ["rapacious", "rapture", "ravage", "ravenous", "surreptitious"] },
  { forms: ["rid", "ris"], meaning: "笑 (laugh)", hint: "ridiculous 荒謬可笑的", examples: ["deride", "ridicule", "risible"] },
  { forms: ["rig"], meaning: "僵硬 (stiff)", examples: ["rigid", "rigorous"] },
  { forms: ["rob"], meaning: "力量 (strength)", examples: ["corroborate", "robust"] },
  { forms: ["rog"], meaning: "問 (ask)", hint: "arrogant 自負的", examples: ["abrogate", "derogate", "interrogate", "surrogate"] },
  { forms: ["rud"], meaning: "粗糙 (rough)", hint: "rude 粗魯的", examples: ["erudite", "rudimentary"] },
  { forms: ["sacr", "secr", "sanct"], meaning: "神聖 (holy)", hint: "sacrifice 犧牲", examples: ["consecrate", "execrate", "sacred", "sacrosanct", "sanctimonious", "sanction"] },
  { forms: ["sal", "sil", "sul"], meaning: "跳 (jump)", hint: "salmon 鮭魚", examples: ["desultory", "exult", "resilient", "salacious", "salient", "salubrious", "salutary"] },
  { forms: ["sci"], meaning: "知道 (know)", hint: "science 科學", examples: ["conscious", "omniscient", "prescient", "unconscionable"] },
  { forms: ["secu", "sequ", "sue"], meaning: "追隨 (follow)", hint: "sequence 順序", examples: ["consecutive", "ensue", "inconsequential", "obsequious"] },
  { forms: ["sed", "sid"], meaning: "坐 (sit)", hint: "sediment 沉積物", examples: ["assiduous", "dissident", "insidious", "sedate", "sedentary", "sedulous", "subside", "supersede"] },
  { forms: ["sens", "sent"], meaning: "感覺 (feel)", hint: "sense 感覺", examples: ["assent", "consensus", "consent", "dissension", "dissent", "presentiment", "resent", "sensational", "sensuous", "sentimental"] },
  { forms: ["spec", "spic"], meaning: "看 (see)", hint: "spectacles 眼鏡", examples: ["auspicious", "circumspect", "conspicuous", "perspicacious", "perspicuous", "retrospect", "specious", "speculate"] },
  { forms: ["tac", "tic"], meaning: "靜默 (silent)", hint: "tacit 心照不宣的", examples: ["reticent", "taciturn"] },
  { forms: ["tain", "ten", "tin"], meaning: "握 (hold)", hint: "obtain 獲得", examples: ["abstain", "abstinence", "countenance", "pertinent", "tenable", "tenacious", "tenet", "tenure"] },
  { forms: ["tend", "tens", "tent", "tenu"], meaning: "延伸、薄弱 (stretch, weak)", hint: "extend 延長", examples: ["attenuate", "contend", "contentious", "distend", "extenuate", "ostensible", "ostentatious", "portend", "portent", "tenuous"] },
  { forms: ["trit"], meaning: "摩擦 (rub)", hint: "attrition 損耗", examples: ["contrite", "detrimental", "diatribe", "trite"] },
  { forms: ["tag", "tig", "tang", "ting"], meaning: "接觸 (touch)", hint: "contagious 接觸傳染的", examples: ["contiguous", "contingent", "tangent", "tangible"] },
  { forms: ["tim"], meaning: "恐懼 (fear)", examples: ["intimidate", "timid", "timorous"] },
  { forms: ["tom"], meaning: "切 (cut)", hint: "anatomy 解剖學", examples: ["dichotomy", "epitome"] },
  { forms: ["tract"], meaning: "拉 (pull)", hint: "attract 吸引", examples: ["abstract", "detract", "intractable", "protracted", "retract", "traction"] },
  { forms: ["trud", "trus"], meaning: "推 (push)", hint: "protrude 凸出", examples: ["abstruse", "intrude", "obtrusive", "thrust"] },
  { forms: ["trench"], meaning: "切 (cut)", hint: "trench 壕溝", examples: ["entrenched", "retrenchment", "trenchant"] },
  { forms: ["turb"], meaning: "攪動 (agitate)", hint: "disturb 打擾", examples: ["imperturbable", "perturb", "turbid", "turbulent"] },
  { forms: ["vac", "van", "void"], meaning: "空 (empty)", hint: "vacuum 真空", examples: ["devoid", "evanescent", "vacuous", "vainglorious", "vanity", "void"] },
  { forms: ["vad", "vas"], meaning: "去、走 (go)", hint: "invade 入侵", examples: ["evade", "pervasive"] },
  { forms: ["val", "vail"], meaning: "強壯、價值 (strong, worth)", hint: "valid 有效力的", examples: ["ambivalent", "equivalent", "prevail", "prevalent", "valediction", "valiant", "validate", "valorize", "valorous"] },
  { forms: ["ven", "vent"], meaning: "去、來 (go, come)", hint: "adventure 冒險", examples: ["advent", "circumvent", "contravene", "convene", "provenance"] },
  { forms: ["ver"], meaning: "真實 (true)", hint: "verify 證實", examples: ["aver", "veracious", "verifiable", "verisimilitude", "verity"] },
  { forms: ["vers", "vert"], meaning: "轉 (turn)", hint: "reverse 逆轉", examples: ["adversarial", "adversary", "adverse", "adversity", "animadversion", "averse", "avert", "controvert", "conversant", "divert", "extroverted", "inadvertent", "introverted", "pervert", "subvert", "versatile", "versed"] },
  { forms: ["via"], meaning: "路 (way)", hint: "via 經由", examples: ["deviate", "devious", "impervious", "obviate", "trivial"] },
  { forms: ["vid", "vis"], meaning: "看 (see)", hint: "video 錄影", examples: ["envision", "improvise", "provident", "providential", "provisional", "prudent", "vista"] },
  { forms: ["vig", "viv"], meaning: "生命 (life)", hint: "survive 倖存", examples: ["convivial", "invigorate", "viable", "vigorous", "vitality", "vivacious"] },
  { forms: ["voc", "vok"], meaning: "聲音 (voice)", hint: "vocal 發聲的；直言的", examples: ["advocate", "equivocal", "evoke", "invoke", "provocative", "revoke", "univocal", "vociferous"] },
  { forms: ["vol"], meaning: "意志 (will)", hint: "volunteer 志工", examples: ["benevolent", "malevolent", "volition"] },
  { forms: ["volu", "volv"], meaning: "捲繞 (roll)", hint: "involve 牽涉", examples: ["convoluted", "devolve", "revolt", "voluble", "voluminous", "welter"] },
  { forms: ["vor", "vour"], meaning: "吃 (eat)", hint: "devour 狼吞虎嚥", examples: ["carnivorous", "herbivorous", "omnivorous", "voracious"] },
];
