// One-off personal mnemonic notes, transcribed from the user's own
// handwritten study notes (a printed GRE-vocab PDF they annotated by
// hand). Applied once to matching words already in the word list by
// applyHandwrittenMnemonicNotes() in app.js — see that function for how
// this is used and why it's keyed this way.
export const HANDWRITTEN_MNEMONIC_NOTES = {
  precarious: "「前有車 → 危險」→ 危險的、不穩定的",
  facile: "make / factory →「做做就好」→ 輕率、過度簡單",
  verifiable: "truth / veracity；補充：corroborate",
  fallacious: "delude (v.)；fallacy (n.) 謬誤",
  specious: "表面看起來 OK 而已",
  spurious: "pure 聯想",
  duplicity: "duplicate →「一個人兩面、雙面人」",
  mendacity: "充滿謊言；補充：disinformation / prevarication",
  concoct: "被拆穿前先變／編；聲音聯想 pre-cocious = 早熟",
  chimera: "Chimera 奇美拉 → 幻想、虛構",
  conjecture: "throw 的聯想",
  surmise: "surpass premise →「越過前提」→ 從不足資訊推測",
  extrapolate: "從已知來推論",
  hyperbole: "超過、誇飾",
  bombastic: "bomb 炸彈 →「炸彈誇」→ 誇大的",
  turgid: "聲音聯想「特激的」→ 枯燥、僵硬不自然",
  ornate: "adorn = 裝飾、ornament",
  quixotic: "Don Quixote 唐吉訶德 → 整天做白日夢、不切實際",
  visionary: "有遠見；另一義：太有遠見而不切實際",
  substantiate: "substance = 物質 → 填充實質證據",
  espouse: "spouse 配偶 →「不可能不支持配偶」→ 支持、擁護",
  champion: "fight for a cause → 為某理念而戰／擁護",
  apostle: "門徒",
  evangelist: "補充聯想：zealot",
  rebut: "over and over／反覆反駁；補充：confute / rebuff / spurn",
  repudiate: "put → reject",
  contradict: "contra = against + dict = say → against say → 反駁",
  gainsay: "against + say",
  impugn: "into fight；補充：impeach = 彈劾",
  debunk: "bunk = nonsense",
  topple: "推翻上位 → subvert",
  undermine: "under + mine →「在下面挖」→ 越來越弱",
  efficacious: "effective",
  fruitful: "充滿水果 → 有成果；反義：fruitless = 未果",
  utilitarian: "utilize = 使用 / utility = 實用性 / practical",
  futile: "flow 掉了的聯想 → 無用",
  perennial: "constant / perennial river = 常年的；補充：thoroughly",
  perpetuate: "聲音聯想「寵物一直存在」",
  ephemeral: "音似一飛就沒了 → 短暫",
  evanescent: "vanish + become → 很快消失",
  transient: "trans = move → 移動、不久留",
  fleeting: "抓不住 → 瞬間",
  momentary: "短暫（對比 momentous = 重要）",
  momentous: "重要（對比 momentary = 短暫）",
  lucid: "bright / 光亮 → 清楚",
  intelligible: "intelligence 聯想 → 能理解的",
  salient: "salmon 鮭魚的聲音聯想；大家一起看同一地方 → noticeable",
  elucidate: "ex + light →「光打出來」→ 闡明",
  explicate: "ex + plic/fold →「資訊折出來」；補充：explicit",
  expound: "ex + put/out → 把內容放出來、詳細解釋",
  elaborate: "拆字聯想：labor",
  accentuate: "accent →「從口音聽出哪裡人」→ 使更明顯",
  underscore: "underline → 強調",
  foreground: "聯想：salient / prominent",
  abstruse: "abstract truth → 難懂",
  arcane: "秘密",
  esoteric: "小圈子 → 只有少數人才懂",
  enigmatic: "enigma → 謎、費解",
  impenetrable: "penetrate = 穿透 → 無法穿透 → 難理解",
  opaque: "不透光 → 引申難懂",
  occult: "神秘、隱密",
  uncanny: "無法用理性理解",
  unfathomable: "fathom = 測深度 → 無法測到底 → 無法理解",
  recondite: "over & over 一直看 → die 都看不懂 → 極深奧",
  ambiguous: "ambi- → 模糊／有多種可能（同組：equivocal / obscure / nebulous，因模糊而不懂）",
  equivocal: "tend to deceive（同組：ambiguous / obscure / nebulous，因模糊而不懂）",
  convoluted: "volu = 捲在一起 / together → 複雜糾纏",
  tortuous: "twist → 彎彎曲曲 → 複雜",
  baffle: "聲音聯想「拜佛」→ 困惑",
  flummox: "「流感」聲音聯想 → 搞得很困惑",
  nonplus: "non + plus →「太困惑，不能再加了」→ 不知所措",
  conundrum: "困難、複雜",
  predicament: "窘境",
  quandary: "聲音聯想「框住你」→ 進退兩難",
};
